Blog app - integration specs for views
toliboff/blog pull request #10
Opened 2021-11-18 14:38 UTC by toliboff

### In this PR were implemented following:
 - Use Capybara to write integration tests for each view in your project.
 - Add integration tests for Login page
 - Add integration tests for User index page:
 - Add integration tests for User show page
 - Add integration tests for Post index page
 - Add integration tests for Post show page

2021-11-18 16:25 UTC, Davidosky007 commented
## Hi @toliboff @m05e5 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the majority of the contribution is one-sided as pair programming was used for this project you are expected to contribute almost equally 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-19 05:35 UTC, Davidosky007 requested changes
## Hi @toliboff @m05e5 👋, 

Good job so far! 💪 
* Descriptive commit messages ✔️ 
* No linter errors ✔️ 
* Proper use of git-flow ✔️ 
* Well written PR ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 05:35 UTC, Davidosky007 commented on spec/views/post_index_spec.rb
> +RSpec.describe 'Post', type: :system do
* I suggest you make Specs file for the integration tests type is `feature` for example ` describe 'the signin process', type: : feature do`

2021-11-19 05:35 UTC, Davidosky007 commented on spec/views/post_show_spec.rb
> +RSpec.describe 'Post', type: :system do
* I suggest you make Specs file for the integration tests type is `feature` for example ` describe 'the signin process', type: : feature do`

2021-11-19 05:35 UTC, Davidosky007 commented on spec/views/user_index_spec.rb
> +RSpec.describe 'Login page', type: :system do
* I suggest you make Specs file for the integration tests type is `feature` for example ` describe 'the signin process', type: : feature do`

2021-11-19 05:35 UTC, Davidosky007 commented on spec/views/user_show_spec.rb
> +RSpec.describe 'User show page', type: :system do
* I suggest you make Specs file for the integration tests type is `feature` for example ` describe 'the signin process', type: : feature do`

2021-11-19 05:35 UTC, Davidosky007 commented on spec/requests/posts_spec.rb
> +#       expect(response).to have_http_status(:ok)
* Kindly remove commented code from your codebase as it makes your codebase bulky and unprofessional 🙏

2021-11-19 07:01 UTC, AshakaE approved these changes
### Hi @toliboff  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 07:26 UTC, merged